default_language_version:
  python: python3.11
repos:
  - repo: local
    hooks:
      - id: npm-lint
        name: Check Linting
        entry: npm run lint
        language: system
        types_or: [javascript, jsx, ts, tsx]
        pass_filenames: true

      - id: npm-prettier
        name: Check Prettier
        entry: npm run format
        language: system
        types_or: [javascript, jsx, ts, tsx]
        pass_filenames: true

      - id: npm-types-check
        name: Check Types
        entry: npm run types-check
        language: system
        types_or: [javascript, jsx, ts, tsx]
        pass_filenames: false

      - id: cdk-synth
        name: CDK Synth
        entry: bash -c 'cd infra && npx cdk synth'
        language: system
        files: ^infra/
        pass_filenames: false

      # - id: npm-test
      #   name: Check Unit Tests
      #   entry: npm run test
      #   language: system
      #   types_or: [javascript, jsx, ts, tsx]
      #   pass_filenames: true

      # - id: npm-test-staged
      #   name: Check Unit Tests for Related Files
      #   entry: npm run test:staged
      #   language: system
      #   types_or: [javascript, jsx, ts, tsx]
      #   pass_filenames: true
