FROM node:22.18.0-alpine AS base

WORKDIR /app
COPY server/package*.json ./
RUN npm install

COPY ./server .

FROM base AS builder

RUN npm run build

FROM node:20.11.1-alpine AS production

WORKDIR /app

COPY ./server/package*.json ./
RUN npm install --production
COPY --from=builder /app/dist/ /app/dist/
# COPY --from=builder /ssl /app/ssl