FROM node:22.18.0-alpine AS base
WORKDIR /app

COPY ./client/package*.json ./
RUN npm install

COPY ./client .

FROM base AS builder

RUN npm run build

FROM nginx:alpine AS production

# COPY /ssl /etc/nginx/ssl
COPY --from=builder /app/dist /usr/share/nginx/html