FROM node:22.18.0-alpine AS base
WORKDIR /app

COPY package*.json ./
COPY services/core/package.json ./services/core/
RUN npm install --workspace=services/core

COPY ./services/core .

FROM base AS builder

RUN npm run build

FROM node:20.11.1-alpine AS production

WORKDIR /app

COPY package*.json ./
COPY services/core/package.json ./services/core/
RUN npm install --workspace=services/core --omit=dev
COPY --from=builder /app/dist/ ./dist/
# COPY --from=builder /ssl /app/ssl

CMD ["node", "dist/src/app.js"]
